"""profile_pic

Revision ID: 3ef49dbc89f6
Revises: da098db6e76b
Create Date: 2018-11-13 13:45:10.013171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef49dbc89f6'
down_revision = 'da098db6e76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilepic', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilepic')
    # ### end Alembic commands ###
